# permissions for end users to view minecrafts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: minecraft-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gamely
    app.kubernetes.io/part-of: gamely
    app.kubernetes.io/managed-by: kustomize
  name: minecraft-viewer-role
rules:
- apiGroups:
  - server.gamely.io
  resources:
  - minecrafts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - server.gamely.io
  resources:
  - minecrafts/status
  verbs:
  - get
