# permissions for end users to edit minecrafts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: minecraft-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gamely
    app.kubernetes.io/part-of: gamely
    app.kubernetes.io/managed-by: kustomize
  name: minecraft-editor-role
rules:
- apiGroups:
  - server.gamely.io
  resources:
  - minecrafts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - server.gamely.io
  resources:
  - minecrafts/status
  verbs:
  - get
