apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gamely.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gamely.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  # TODO: Trim this down to the required permissions
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io