apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamely.fullname" . }}
  labels:
    {{- include "gamely.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gamely.selectorLabels" . | nindent 4 }}
