apiVersion: server.gamely.io/v1alpha1
kind: Valheim
metadata:
  labels:
    app.kubernetes.io/name: valheim
    app.kubernetes.io/instance: valheim-sample
    app.kubernetes.io/part-of: gamely
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gamely
  name: valheim-sample
spec:
  server:
    name: "Test Server"
    worldNameOrSeed: "dedicated"
    additionalEnv:
      test: "truemoasdfasdfre"
  service:
    type: NodePort
  backups:
    secretKeyRef:
      name: backups
    endpoint: minio.default:9000
    bucket: backups
    storage:
      size: 6Gi
  storage:
    size: 2Gi
  hooks:
    postBackupHook: |
      echo "Backup created at @BACKUP_FILE@"
  mods:
    enabled: true
    framework: bepinex
    storage:
      size: 1Gi
    packages:
      "SpikeHimself/XPortal":
        version: 1.2.19
      "ValheimModding/Jotunn":
        version: 2.15.1
  access:
    admins:
      - "76561198984891671" # testarooni