name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Operator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: go mod download
      - run: |
          formatted_count=$(gofmt -s -l . | wc -l)
          if [ "${formatted_count}" -ne 0 ] ; then
            echo "Run 'go fmt github.com/robwittman/gamely...'"
            exit 1
          fi

  test:
    name: Test Operator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: go mod download
      - run: go build -v ./...
      - run: go test -v ./... -cover
